# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm" # Use npm for a Node.js project
    directory: "/" # The root directory of your project
    schedule:
      interval: "weekly" # Dependabot will check for updates every week
  - package-ecosystem: "pip" # For Python projects, replace with your relevant ecosystem
    directory: "/"
    schedule:
      interval: "monthly"
